/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdTriggersRouteImport } from './routes/projects/$projectId/triggers'
import { Route as ProjectsProjectIdSqlRouteImport } from './routes/projects/$projectId/sql'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdSchemaRouteImport } from './routes/projects/$projectId/schema'
import { Route as ProjectsProjectIdRealtimeRouteImport } from './routes/projects/$projectId/realtime'
import { Route as ProjectsProjectIdMcpRouteImport } from './routes/projects/$projectId/mcp'
import { Route as ProjectsProjectIdLogsRouteImport } from './routes/projects/$projectId/logs'
import { Route as ProjectsProjectIdKeysRouteImport } from './routes/projects/$projectId.keys'
import { Route as ProjectsProjectIdFunctionsRouteImport } from './routes/projects/$projectId/functions'
import { Route as ProjectsProjectIdExtensionsRouteImport } from './routes/projects/$projectId/extensions'
import { Route as ProjectsProjectIdEnumsRouteImport } from './routes/projects/$projectId/enums'
import { Route as ProjectsProjectIdAuthRouteImport } from './routes/projects/$projectId.auth'
import { Route as ProjectsProjectIdTablesIndexRouteImport } from './routes/projects/$projectId/tables/index'
import { Route as ProjectsProjectIdTablesTableNameRouteImport } from './routes/projects/$projectId/tables/$tableName'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTriggersRoute =
  ProjectsProjectIdTriggersRouteImport.update({
    id: '/triggers',
    path: '/triggers',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSqlRoute = ProjectsProjectIdSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSchemaRoute = ProjectsProjectIdSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdRealtimeRoute =
  ProjectsProjectIdRealtimeRouteImport.update({
    id: '/realtime',
    path: '/realtime',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdMcpRoute = ProjectsProjectIdMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdLogsRoute = ProjectsProjectIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdKeysRoute = ProjectsProjectIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdFunctionsRoute =
  ProjectsProjectIdFunctionsRouteImport.update({
    id: '/functions',
    path: '/functions',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdExtensionsRoute =
  ProjectsProjectIdExtensionsRouteImport.update({
    id: '/extensions',
    path: '/extensions',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdEnumsRoute = ProjectsProjectIdEnumsRouteImport.update({
  id: '/enums',
  path: '/enums',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAuthRoute = ProjectsProjectIdAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTablesIndexRoute =
  ProjectsProjectIdTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTablesTableNameRoute =
  ProjectsProjectIdTablesTableNameRouteImport.update({
    id: '/tables/$tableName',
    path: '/tables/$tableName',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectId/auth': typeof ProjectsProjectIdAuthRoute
  '/projects/$projectId/enums': typeof ProjectsProjectIdEnumsRoute
  '/projects/$projectId/extensions': typeof ProjectsProjectIdExtensionsRoute
  '/projects/$projectId/functions': typeof ProjectsProjectIdFunctionsRoute
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/mcp': typeof ProjectsProjectIdMcpRoute
  '/projects/$projectId/realtime': typeof ProjectsProjectIdRealtimeRoute
  '/projects/$projectId/schema': typeof ProjectsProjectIdSchemaRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/sql': typeof ProjectsProjectIdSqlRoute
  '/projects/$projectId/triggers': typeof ProjectsProjectIdTriggersRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tables/$tableName': typeof ProjectsProjectIdTablesTableNameRoute
  '/projects/$projectId/tables/': typeof ProjectsProjectIdTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/$projectId/auth': typeof ProjectsProjectIdAuthRoute
  '/projects/$projectId/enums': typeof ProjectsProjectIdEnumsRoute
  '/projects/$projectId/extensions': typeof ProjectsProjectIdExtensionsRoute
  '/projects/$projectId/functions': typeof ProjectsProjectIdFunctionsRoute
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/mcp': typeof ProjectsProjectIdMcpRoute
  '/projects/$projectId/realtime': typeof ProjectsProjectIdRealtimeRoute
  '/projects/$projectId/schema': typeof ProjectsProjectIdSchemaRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/sql': typeof ProjectsProjectIdSqlRoute
  '/projects/$projectId/triggers': typeof ProjectsProjectIdTriggersRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tables/$tableName': typeof ProjectsProjectIdTablesTableNameRoute
  '/projects/$projectId/tables': typeof ProjectsProjectIdTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectId/auth': typeof ProjectsProjectIdAuthRoute
  '/projects/$projectId/enums': typeof ProjectsProjectIdEnumsRoute
  '/projects/$projectId/extensions': typeof ProjectsProjectIdExtensionsRoute
  '/projects/$projectId/functions': typeof ProjectsProjectIdFunctionsRoute
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/mcp': typeof ProjectsProjectIdMcpRoute
  '/projects/$projectId/realtime': typeof ProjectsProjectIdRealtimeRoute
  '/projects/$projectId/schema': typeof ProjectsProjectIdSchemaRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/sql': typeof ProjectsProjectIdSqlRoute
  '/projects/$projectId/triggers': typeof ProjectsProjectIdTriggersRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tables/$tableName': typeof ProjectsProjectIdTablesTableNameRoute
  '/projects/$projectId/tables/': typeof ProjectsProjectIdTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectId/auth'
    | '/projects/$projectId/enums'
    | '/projects/$projectId/extensions'
    | '/projects/$projectId/functions'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/mcp'
    | '/projects/$projectId/realtime'
    | '/projects/$projectId/schema'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sql'
    | '/projects/$projectId/triggers'
    | '/projects/$projectId/'
    | '/projects/$projectId/tables/$tableName'
    | '/projects/$projectId/tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects'
    | '/settings'
    | '/projects/$projectId/auth'
    | '/projects/$projectId/enums'
    | '/projects/$projectId/extensions'
    | '/projects/$projectId/functions'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/mcp'
    | '/projects/$projectId/realtime'
    | '/projects/$projectId/schema'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sql'
    | '/projects/$projectId/triggers'
    | '/projects/$projectId'
    | '/projects/$projectId/tables/$tableName'
    | '/projects/$projectId/tables'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectId/auth'
    | '/projects/$projectId/enums'
    | '/projects/$projectId/extensions'
    | '/projects/$projectId/functions'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/mcp'
    | '/projects/$projectId/realtime'
    | '/projects/$projectId/schema'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sql'
    | '/projects/$projectId/triggers'
    | '/projects/$projectId/'
    | '/projects/$projectId/tables/$tableName'
    | '/projects/$projectId/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/triggers': {
      id: '/projects/$projectId/triggers'
      path: '/triggers'
      fullPath: '/projects/$projectId/triggers'
      preLoaderRoute: typeof ProjectsProjectIdTriggersRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/sql': {
      id: '/projects/$projectId/sql'
      path: '/sql'
      fullPath: '/projects/$projectId/sql'
      preLoaderRoute: typeof ProjectsProjectIdSqlRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/schema': {
      id: '/projects/$projectId/schema'
      path: '/schema'
      fullPath: '/projects/$projectId/schema'
      preLoaderRoute: typeof ProjectsProjectIdSchemaRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/realtime': {
      id: '/projects/$projectId/realtime'
      path: '/realtime'
      fullPath: '/projects/$projectId/realtime'
      preLoaderRoute: typeof ProjectsProjectIdRealtimeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/mcp': {
      id: '/projects/$projectId/mcp'
      path: '/mcp'
      fullPath: '/projects/$projectId/mcp'
      preLoaderRoute: typeof ProjectsProjectIdMcpRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/logs': {
      id: '/projects/$projectId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/logs'
      preLoaderRoute: typeof ProjectsProjectIdLogsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/keys': {
      id: '/projects/$projectId/keys'
      path: '/keys'
      fullPath: '/projects/$projectId/keys'
      preLoaderRoute: typeof ProjectsProjectIdKeysRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/functions': {
      id: '/projects/$projectId/functions'
      path: '/functions'
      fullPath: '/projects/$projectId/functions'
      preLoaderRoute: typeof ProjectsProjectIdFunctionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/extensions': {
      id: '/projects/$projectId/extensions'
      path: '/extensions'
      fullPath: '/projects/$projectId/extensions'
      preLoaderRoute: typeof ProjectsProjectIdExtensionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/enums': {
      id: '/projects/$projectId/enums'
      path: '/enums'
      fullPath: '/projects/$projectId/enums'
      preLoaderRoute: typeof ProjectsProjectIdEnumsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/auth': {
      id: '/projects/$projectId/auth'
      path: '/auth'
      fullPath: '/projects/$projectId/auth'
      preLoaderRoute: typeof ProjectsProjectIdAuthRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tables/': {
      id: '/projects/$projectId/tables/'
      path: '/tables'
      fullPath: '/projects/$projectId/tables/'
      preLoaderRoute: typeof ProjectsProjectIdTablesIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tables/$tableName': {
      id: '/projects/$projectId/tables/$tableName'
      path: '/tables/$tableName'
      fullPath: '/projects/$projectId/tables/$tableName'
      preLoaderRoute: typeof ProjectsProjectIdTablesTableNameRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAuthRoute: typeof ProjectsProjectIdAuthRoute
  ProjectsProjectIdEnumsRoute: typeof ProjectsProjectIdEnumsRoute
  ProjectsProjectIdExtensionsRoute: typeof ProjectsProjectIdExtensionsRoute
  ProjectsProjectIdFunctionsRoute: typeof ProjectsProjectIdFunctionsRoute
  ProjectsProjectIdKeysRoute: typeof ProjectsProjectIdKeysRoute
  ProjectsProjectIdLogsRoute: typeof ProjectsProjectIdLogsRoute
  ProjectsProjectIdMcpRoute: typeof ProjectsProjectIdMcpRoute
  ProjectsProjectIdRealtimeRoute: typeof ProjectsProjectIdRealtimeRoute
  ProjectsProjectIdSchemaRoute: typeof ProjectsProjectIdSchemaRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdSqlRoute: typeof ProjectsProjectIdSqlRoute
  ProjectsProjectIdTriggersRoute: typeof ProjectsProjectIdTriggersRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdTablesTableNameRoute: typeof ProjectsProjectIdTablesTableNameRoute
  ProjectsProjectIdTablesIndexRoute: typeof ProjectsProjectIdTablesIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAuthRoute: ProjectsProjectIdAuthRoute,
  ProjectsProjectIdEnumsRoute: ProjectsProjectIdEnumsRoute,
  ProjectsProjectIdExtensionsRoute: ProjectsProjectIdExtensionsRoute,
  ProjectsProjectIdFunctionsRoute: ProjectsProjectIdFunctionsRoute,
  ProjectsProjectIdKeysRoute: ProjectsProjectIdKeysRoute,
  ProjectsProjectIdLogsRoute: ProjectsProjectIdLogsRoute,
  ProjectsProjectIdMcpRoute: ProjectsProjectIdMcpRoute,
  ProjectsProjectIdRealtimeRoute: ProjectsProjectIdRealtimeRoute,
  ProjectsProjectIdSchemaRoute: ProjectsProjectIdSchemaRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdSqlRoute: ProjectsProjectIdSqlRoute,
  ProjectsProjectIdTriggersRoute: ProjectsProjectIdTriggersRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdTablesTableNameRoute: ProjectsProjectIdTablesTableNameRoute,
  ProjectsProjectIdTablesIndexRoute: ProjectsProjectIdTablesIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
