"""Database-per-project provisioner.

Connects as Postgres superuser to create an isolated database and
dedicated user for each project.
"""

from __future__ import annotations

import re
import secrets
import uuid
from typing import Any

import asyncpg
import structlog

logger = structlog.get_logger()

# Strict allowlist: only lowercase alphanumeric and underscore.
# All identifiers we generate match this pattern (pqdb_project_<hex>,
# pqdb_user_<hex>), so this is a defense-in-depth check.
_SAFE_IDENTIFIER_RE = re.compile(r"^[a-z0-9_]+$")


class ProvisioningError(Exception):
    """Raised when database provisioning fails."""


def _validate_identifier(name: str) -> str:
    """Validate that a SQL identifier contains only safe characters.

    PostgreSQL DDL (CREATE DATABASE, CREATE USER) does not support
    parameterized queries.  Since we generate these identifiers from
    UUIDs, they are never user-controlled.  This validation is
    defense-in-depth to ensure no special characters can slip through.

    Raises ValueError if the identifier contains unsafe characters.
    """
    if not _SAFE_IDENTIFIER_RE.match(name):
        msg = f"Unsafe SQL identifier rejected: {name!r}"
        raise ValueError(msg)
    return name


def make_database_name(project_id: uuid.UUID) -> str:
    """Generate a database name from a project UUID.

    Format: pqdb_project_{first 12 hex chars of uuid}
    """
    return f"pqdb_project_{project_id.hex[:12]}"


def make_project_user(project_id: uuid.UUID) -> str:
    """Generate a database username from a project UUID.

    Format: pqdb_user_{first 12 hex chars of uuid}
    """
    return f"pqdb_user_{project_id.hex[:12]}"


def _build_create_user_sql(user: str, password: str) -> str:
    """Build a CREATE USER statement with validated identifier.

    The user identifier is validated against a strict allowlist.
    The password is generated by secrets.token_urlsafe and is not
    user-controlled.
    """
    _validate_identifier(user)
    return "CREATE USER " + user + " WITH PASSWORD '" + password + "'"  # noqa: S608


def _build_create_database_sql(db_name: str) -> str:
    """Build a CREATE DATABASE statement with validated identifier."""
    _validate_identifier(db_name)
    return "CREATE DATABASE " + db_name  # noqa: S608


def _build_grant_connect_sql(db_name: str, user: str) -> str:
    """Build a GRANT CONNECT statement with validated identifiers."""
    _validate_identifier(db_name)
    _validate_identifier(user)
    return "GRANT CONNECT ON DATABASE " + db_name + " TO " + user  # noqa: S608


class DatabaseProvisioner:
    """Provisions isolated Postgres databases for projects."""

    def __init__(self, superuser_dsn: str) -> None:
        self.superuser_dsn = superuser_dsn

    async def provision(self, project_id: uuid.UUID) -> str:
        """Create a new database and user for the given project.

        Returns the database name on success.
        Raises ProvisioningError on failure.
        """
        db_name = make_database_name(project_id)
        db_user = make_project_user(project_id)
        db_password = secrets.token_urlsafe(32)

        conn: Any = None
        try:
            conn = await asyncpg.connect(self.superuser_dsn)

            create_user_sql = _build_create_user_sql(db_user, db_password)
            await conn.execute(create_user_sql)

            create_db_sql = _build_create_database_sql(db_name)
            await conn.execute(create_db_sql)

            grant_sql = _build_grant_connect_sql(db_name, db_user)
            await conn.execute(grant_sql)

            logger.info(
                "database_provisioned",
                project_id=str(project_id),
                database_name=db_name,
                database_user=db_user,
            )

            return db_name

        except ProvisioningError:
            raise
        except Exception as exc:
            logger.error(
                "provisioning_failed",
                project_id=str(project_id),
                error=str(exc),
            )
            raise ProvisioningError(str(exc)) from exc
        finally:
            if conn is not None:
                await conn.close()
